export default {
	LOGIN_SUCCESS: 'LOGIN_SUCCESS',
	LOGIN_FAIL: 'LOGIN_FAIL',
	REGISTER_SUCCESS: 'REGISTER_SUCCESS',
	REGISTER_FAIL: 'REGISTER_FAIL',
	GET_USER_SUCCESS: 'GET_USER_SUCCESS',
	GET_USER_FAIL: 'GET_USER_FAIL',
	RESET_STORE: 'RESET_STORE'
}